version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          command: sleep 100
      - run:
          command: "echo Hello, World!"
          when: always

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
