version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          command: echo "Ready to deploy" 

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run: 
          name: Deployment
          command: echo "Success!" 

workflows:
  build-hold-deploy:
    jobs:
      - build
      - deploy:
          context: permission
